spring:
    application:
        name: CONFIG-SERVER

# git location for config server repo
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/mavericakaviggu/config-server-repo
                    clone-on-start: true
                    default-label: main

server:
    port: 8888

# Eureka server configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
