# Server port
server:
  port: 8084
  servlet:
    context-path: /api/v1.0

# Database configuration
spring:
  datasource:
     url: jdbc:mysql://localhost:3306/auth_db?useSSL=false
     username: root
     password: root4977
     driver-class-name: com.mysql.cj.jdbc.Driver
# spring:
  application:
    name: AUTH-SERVICE
  config:
    import: optional:configserver:http://localhost:8888
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
     hibernate:
       ddl-auto: update
     show-sql: true
# #  below details are for sending email fetched from brevo.com (masked for security purposes)
#   mail: 
#     host: smtp-relay.brevo.com
#     port: 587
#     username: ***@smtp-brevo.com
#     password: *************
#     properties:
#       mail.smtp.auth: true
#       mail.smtp.starttls.enable: true
#       mail.smtp.from: vigneshshet4577@gmail.com
#     protocol: smtp
   

# ===================== JWT CONFIG =====================
# app:
#   jwt:
#     secret: MySecretKey1234567890!@#      # You should use a stronger key in prod
#     expiration: 3600000   # 1 hour in milliseconds (1000 * 60 * 60)
    
jwt:
  secret:
    key: thisisthesecretkeywhichihaveuserforthefirsttime

logging:
  level.org.springframework.security: DEBUG           