# Server port
server:
  port: 8084
  servlet:
    context-path: /api/v1.0

# Database configuration
spring:
  datasource:
     url: jdbc:mysql://localhost:3306/auth_db?useSSL=false
     username: root
     password: root4977
     driver-class-name: com.mysql.cj.jdbc.Driver
# spring:
  application:
    name: AUTH-SERVICE
  config:
    import: optional:configserver:http://localhost:8888
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
     hibernate:
       ddl-auto: update
     show-sql: true

# ===================== JWT CONFIG =====================
# app:
#   jwt:
#     secret: MySecretKey1234567890!@#      # You should use a stronger key in prod
#     expiration: 3600000   # 1 hour in milliseconds (1000 * 60 * 60)
    
jwt:
  secret:
    key: thisisthesecretkeywhichihaveuserforthefirsttime           