spring:
    datasource:
        url: jdbc:mysql://localhost:3306/organization_db?useSSL=false
        username: root
        password: root4977
        driver-class-name: com.mysql.cj.jdbc.Driver
# spring:
    application:
        name: ORGANIZATION-SERVICE
    config:
        import: optional:configserver:http://localhost:8888
    # rabbitmq:
    #     host: localhost
    #     port: 5672
    #     username: guest
    #     password: guest

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

server:
    port: 8083

# # Eureka server configuration
eureka:
   client:
     service-url:
       defaultZone: http://localhost:8761/eureka
